# Change these first
owner: eosc-synergy # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: SQAaaS Web
    url: https://sqaaas.eosc-synergy.eu/
    icon: https://upload.wikimedia.org/wikipedia/commons/a/ab/Swagger-logo.png
  - name: SQAaaS API - production
    url: https://api.sqaaas.eosc-synergy.eu/v1/
    icon: https://upload.wikimedia.org/wikipedia/commons/a/ab/Swagger-logo.png
    expectedStatusCodes:
      - 403
  - name: SQAaaS API - staging
    url: https://api-staging.sqaaas.eosc-synergy.eu/v1/
    icon: https://upload.wikimedia.org/wikipedia/commons/a/ab/Swagger-logo.png
    expectedStatusCodes:
      - 403
  - name: SQAaaS API - development
    url: https://api-dev.sqaaas.eosc-synergy.eu/pipeline
    icon: https://www.eosc-synergy.eu/wp-content/uploads/EOSC-Synergy-Logo-mini-png.png
  - name: Jenkins
    url: https://jenkins.eosc-synergy.eu/
    icon: https://cdn.imgbin.com/11/2/21/imgbin-jenkins-docker-continuous-delivery-installation-software-deployment-github-Dm3vXdSYp61UevYTam2zCT0D0.jpg
  
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.eosc-synergy.eu
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://www.eosc-synergy.eu/wp-content/uploads/EOSC-Synergy-Logo-mini-png.png
  name: UEOSC Synergy service status
  introTitle: EOSC Synergy service status
  introMessage: Live status page of [EOSC Synergy](https://eosc-synergy.eu) services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
